### ISSUE TITLE
When you supply the database configuration directory as a relative path, the execution fails.

### ISSUE THREAD

**Issue by paulissoft** [paulissoft/oracle-tools-gui#5]
```
D:\>python oracle-tools-gui/src/oracle_tools_gui.py --db-config-dir oracle-tools/conf/src oracle-tools-examples/db/pom.xml
Current directory: D:/

INFO:Version of "mvn" is "3.6.3" and its location is "C:\usr\local\apache-maven-3.6.3\bin"
INFO:Version of "perl" is "5.30.0" and its location is "c:\Strawberry\perl\bin"
INFO:Version of "sql" is "19.1.0.0" and its location is "C:\usr\local\sqlcl\bin"
INFO:Version of "java" is "17.0.2" and its location is "C:\Program Files\Common Files\Oracle\Java\javapath"
INFO:Version of "javac" is "17.0.2" and its location is "C:\Program Files\Common Files\Oracle\Java\javapath"
Traceback (most recent call last):
  File "D:\oracle-tools-gui\src\oracle_tools_gui.py", line 190, in <module>
    main()
  File "D:\oracle-tools-gui\src\oracle_tools_gui.py", line 184, in main
    run_POM_file_gui(args.file, args.db_config_dir)
  File "C:\Users\gjpau\miniconda3\envs\bc\lib\site-packages\gooey\python_bindings\gooey_decorator.py", line 128, in inner2
    return payload(*args, **kwargs)
  File "D:\oracle-tools-gui\src\oracle_tools_gui.py", line 92, in run_POM_file_gui
    db_config_dir, dbs, profiles, db_proxy_username, db_username = process_POM(pom_file, db_config_dir)
  File "D:\oracle-tools-gui\src\utils\pom.py", line 130, in process_POM
    properties, profiles = determine_POM_settings(pom_file, db_config_dir)
  File "D:\oracle-tools-gui\src\utils\pom.py", line 108, in determine_POM_settings
    raise Exception(f'The command "{cmd}" failed with return code {returncode} and error:\n{error}')
Exception: The command "mvn --file oracle-tools-examples/db/pom.xml -N help:all-profiles -Pconf-inquiry compile -Ddb.config.dir=oracle-tools/conf/src" failed with return code 1 and error:
```

**Comment by paulissoft** [comment]
The point is that mvn changes its working directory to the directory of the POM file and then the database configuration directory may not be correct anymore.

Solved by converting the database configuration directory **and** the POM file on the command line to absolute file paths.
